version: "3"
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: filophile
      POSTGRES_DB: filophile_development
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      target: base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://filophile:password@db:5432/filophile_development
      RAILS_ENV: development
    depends_on:
      - db

  test:
    build:
      context: .
      target: base
    command: bundle exec rspec
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://filophile:password@db:5432/filophile_test
      RAILS_ENV: test
    depends_on:
      - db

volumes:
  postgres_data:
